apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    user: postgres
    database: dt_bharath
    secureJsonData:
      password: postgres123
    jsonData:
      sslmode: disable
      connMaxLifetime: 14400
      maxOpenConns: 100
      maxIdleConns: 100
      postgresVersion: 1500
